services:

  fleet-db:
    image: postgres:15-alpine
    container_name: fleet-db
    environment:
      POSTGRES_DB: fleet_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - fleet-data:/var/lib/postgresql/data
    networks:
      - fleetguard-net

  rules-alerts-db:
    image: postgres:15-alpine
    container_name: rules-alerts-db
    environment:
      POSTGRES_DB: rules_alerts_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - rules-data:/var/lib/postgresql/data
    networks:
      - fleetguard-net

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmqfleet
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - fleetguard-net
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 5

  fleet-service:
    build:
      context: .
      dockerfile: fleet-service/Dockerfile
    container_name: fleet-service
    depends_on:
      fleet-db:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://fleet-db:5432/fleet_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
      SERVER_PORT: 8080
    ports:
      - "8081:8080"
    networks:
      - fleetguard-net

  rules-alerts-service:
    build:
      context: .
      dockerfile: rules-alerts-service/Dockerfile
    container_name: rules-alerts-service
    depends_on:
      rules-alerts-db:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://rules-alerts-db:5432/rules_alerts_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
      SERVER_PORT: 8080
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8093:8080"
    networks:
      - fleetguard-net

volumes:
  fleet-data:
  rules-data:
  rabbitmq-data:

networks:
  fleetguard-net:
    driver: bridge