import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-variant": "#e0e3e5",
        "primary-fixed-dim": "#adc7f7",
        "tertiary-fixed-dim": "#f8bc4b",
        "on-error-container": "#93000a",
        "secondary-container": "#8ef5b5",
        "secondary-fixed": "#91f8b8",
        "on-secondary-container": "#007243",
        "on-background": "#181c1e",
        "outline": "#74777f",
        "surface-container-highest": "#e0e3e5",
        "on-secondary": "#ffffff",
        "inverse-on-surface": "#eef1f3",
        "on-surface-variant": "#43474e",
        "on-primary-fixed": "#001b3c",
        "primary-fixed": "#d6e3ff",
        "primary-container": "#1a365d",
        "inverse-primary": "#adc7f7",
        "tertiary": "#2d1d00",
        "surface": "#f7fafc",
        "surface-container-low": "#f1f4f6",
        "surface-dim": "#d7dadc",
        "tertiary-fixed": "#ffdeaa",
        "background": "#f7fafc",
        "on-tertiary-fixed": "#271900",
        "on-tertiary-container": "#cb9524",
        "surface-bright": "#f7fafc",
        "tertiary-container": "#493100",
        "error": "#ba1a1a",
        "on-primary": "#ffffff",
        "surface-container-high": "#e5e9eb",
        "surface-container-lowest": "#ffffff",
        "on-primary-container": "#86a0cd",
        "surface-tint": "#455f88",
        "on-tertiary-fixed-variant": "#5f4100",
        "surface-container": "#ebeef0",
        "error-container": "#ffdad6",
        "secondary": "#006d40",
        "on-secondary-fixed-variant": "#00522f",
        "on-error": "#ffffff",
        "on-secondary-fixed": "#002110",
        "on-tertiary": "#ffffff",
        "inverse-surface": "#2d3133",
        "primary": "#002045",
        "secondary-fixed-dim": "#74db9d",
        "on-surface": "#181c1e",
        "outline-variant": "#c4c6cf",
        "on-primary-fixed-variant": "#2d476f",
      },
    },
  },
  plugins: [],
};
export default config;
